name: Sync Notes to Portfolio

on:
  push:
    branches:
      - test-github-actions  # ou la branche où vos notes sont mises à jour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Garden Repository
        uses: actions/checkout@v3

      - name: Checkout Portfolio Repository
        uses: actions/checkout@v3
        with:
          repository: issamsisbane/portfolio  # Remplacez par votre nom d'utilisateur et le nom du dépôt portfolio
          token: ${{ secrets.PORTFOLIO_SECRET_TOKEN }}
          path: portfolio
          ref: test-github-actions

      - name: Copy New Notes
        run: |
          rsync -av --ignore-existing garden/content/blog/ portfolio/src/content/blog/en/
          cd portfolio
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add .
          git diff-index --quiet HEAD || git commit -m "Sync notes from garden"
          git push test-github-actions
