name: Sync Notes to Portfolio

on:
  push:
    branches:
      - test-github-actions  # ou la branche où vos notes sont mises à jour

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Garden Repository
        uses: actions/checkout@v3

      - name: Checkout Portfolio Repository
        uses: actions/checkout@v3
        with:
          repository: issamsisbane/portfolio  # Remplacez par votre nom d'utilisateur et le nom du dépôt portfolio
          token: ${{ secrets.PORTFOLIO_SECRET_TOKEN }}
          path: portfolio
          ref: test-github-actions

      ## Translate Notes

      ## Copy Assets from Garden
      - name: Copy assets from garden
        run: |
          find ./content -type f \( -name "*.md" -o -name "*.markdown" \) | while read -r file; do
            grep -oP '!\[\[[^\]]+\]\]' "$file" | while read -r match; do
              image=$(echo "$match" | sed -E 's/!\[\[|\]\]//g')
              if [[ ! -f "./assets/$image" ]]; then
                  echo "Image not found: $image in $file"
              else
                  echo "Image found: $image in $file"
                  cp "./assets/$image" "./portfolio/public/$image"
              fi
            done
          done

      ## Get Assets from Notes
      - name: Copy new notes
        run: |
          rsync -av --ignore-existing content/blog/ portfolio/src/content/blog/en/
          cd portfolio
          find . -type f \( -name "*.md" -o -name "*.markdown" \) | while read -r file; do
              sed -i -E "s|!\[\[(.*?)\]\]|![]($new_prefix\1)|g" "$file"
          done
      
      ## Copy Notes and Assets From Garden
      - name: Commit
        run: |
          cd portfolio
          git status
# git config --global user.name "github-actions"
# git config --global user.email "github-actions@github.com"
# git add .
# git diff-index --quiet HEAD || git commit -m "Sync notes from garden"
# git push origin test-github-actions
