name: Traduction conditionnelle multi-dossiers

on:
  push:
    paths:
      - 'content/**'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install google-genai

    - name: Trouver fichiers à traduire (fr ↔ en)
      id: find_files
      run: |
        files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^content/' || true)

        to_translate=""

        for f in $files; do
          if [[ "$f" =~ /fr/ ]]; then
            en_file="${f/\/fr\//\/en\/}"
            if [ ! -f "$en_file" ]; then
              to_translate="$to_translate $f"
            fi
          elif [[ "$f" =~ /en/ ]]; then
            fr_file="${f/\/en\//\/fr\/}"
            if [ ! -f "$fr_file" ]; then
              to_translate="$to_translate $f"
            fi
          fi
        done

        echo "files=$to_translate" >> $GITHUB_OUTPUT 

    - name: Traduire fichiers modifiés
      env:
        GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
      run: |
        for file in ${{ steps.find_files.outputs.files }}; do
          echo "Traduction: $file"
          python3 .github/scripts/translate.py "$file"
        done
        
    - name: Commit & push fichiers traduits
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add contents/**/fr/** contents/**/en/**
        git diff --cached --quiet || (git commit -m "Traductions automatiques via Gemini" && git push)